---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: load-generator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: load-generator
    helm.sh/chart: {{ include "aws-appmesh-demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  meshName: appmesh
  backends:
    # Allow outbound communication to the nginx service
    - virtualService:
        virtualServiceName: nginx.appmesh-demo.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: load-generator
    helm.sh/chart: {{ include "aws-appmesh-demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: load-generator
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-generator
    spec:
      containers:
        - name: loader
          ports:
            - containerPort: 80
          image: skandyla/wrk:latest
          command: ["/usr/local/bin/wrk"]
          args: ["-c400", "-t8", "-d1h", 
            "http://nginx.appmesh-demo.svc.cluster.local"]
